version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ../01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../01-mosquitto/users:/mosquitto/config/users
      - /home/dux/Smartlab/data/mosquitto/data:/mosquitto/data
      - /home/dux/Smartlab/data/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /home/dux/Smartlab/data/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:8.2.0
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /home/dux/Smartlab/data/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://147.142.19.112:3000/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=ultracold.smartlab@gmail.com
      - GF_SMTP_FROM_ADDRESS=ultracold.smartlab@gmail.com
      - GF_SMTP_PASSWORD=9s9*NzTWDUfl
      - GF_RENDERING_CALLBACK_URL=http://147.142.19.112:3000/
    restart: always

  mqttbridge:
    build: ../02-bridge
    image: iotohn/mqttbridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: always
